import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/myui/Navbar";

export const metadata: Metadata = {
  title: "Practice Folder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-1">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
